# {updated by mmm: Sun Sep 22 14:43:38 2024 GMT}
# {flags: -a+ -e- -l- -L+ -m- -1- -v-}
# {rules}
.SUFFIXES:
.SUFFIXES:	.o .sy .m2 .d
MFLAGS =	
M2C =		m2c
.m2.o:
		$(M2C) -c $(MFLAGS) $*.m2
.d.a:
		$(M2C) $(MFLAGS) $*.d
# {macros}
SRC =		MCArgs.d MCArgs.m2 MCBase.d MCBase.m2 MCBigSet.d MCBigSet.m2 \
		MCFatal.d MCFatal.m2 MCHalfword.d MCHalfword.m2 MCKey.m2 \
		MCKey.d MCMain.m2 MCMnemonics.d MCMnemonics.m2 MCOperation.d \
		MCOperation.m2 MCP1IO.d MCP1IO.m2 MCP1Ident.d MCP1Ident.m2 \
		MCP1Public.d MCP1Public.m2 MCP1Reals.d MCP1Reals.m2 MCP2IO.d \
		MCP2IO.m2 MCP2Ident.d MCP2Ident.m2 MCP2Public.d \
		MCP2Public.m2 MCP2Referen.d MCP2Referen.m2 MCP3IO.d \
		MCP3IO.m2 MCP3Ident.d MCP3Ident.m2 MCP3Public.d \
		MCP3Public.m2 MCP4Attribu.d MCP4Attribu.m2 MCP4BasicOp.d \
		MCP4BasicOp.m2 MCP4Blocks.d MCP4Blocks.m2 MCP4CodeSys.d \
		MCP4CodeSys.m2 MCP4Expr.d MCP4Expr.m2 MCP4Global.d \
		MCP4Global.m2 MCP4In.d MCP4In.m2 MCP4Public.d MCP4Public.m2 \
		MCP4Registe.d MCP4Registe.m2 MCP4Scanner.d MCP4Scanner.m2 \
		MCP4Stack.d MCP4Stack.m2 MCP4Stateme.d MCP4Stateme.m2 \
		MCP4Types.d MCP4Types.m2 MCPass1.d MCPass1.m2 MCPass2.d \
		MCPass2.m2 MCPass3.d MCPass3.m2 MCPass4.d MCPass4.m2 \
		MCSuffixes.d MCSuffixes.m2 MCSymFile.d MCSymFile.m2 \
		MCSymFileDe.d MCSymFileDe.m2 MCTypes.d MCTypes.m2 Memory.d \
		Memory.m2
TAGSRC =	MCArgs.m2 MCBase.m2 MCBigSet.m2 MCFatal.m2 MCHalfword.m2 \
		MCKey.m2 MCMain.m2 MCMnemonics.m2 MCOperation.m2 MCP1IO.m2 \
		MCP1Ident.m2 MCP1Public.m2 MCP1Reals.m2 MCP2IO.m2 \
		MCP2Ident.m2 MCP2Public.m2 MCP2Referen.m2 MCP3IO.m2 \
		MCP3Ident.m2 MCP3Public.m2 MCP4Attribu.m2 MCP4BasicOp.m2 \
		MCP4Blocks.m2 MCP4CodeSys.m2 MCP4Expr.m2 MCP4Global.m2 \
		MCP4In.m2 MCP4Public.m2 MCP4Registe.m2 MCP4Scanner.m2 \
		MCP4Stack.m2 MCP4Stateme.m2 MCP4Types.m2 MCPass1.m2 \
		MCPass2.m2 MCPass3.m2 MCPass4.m2 MCSuffixes.m2 MCSymFile.m2 \
		MCSymFileDe.m2 MCTypes.m2 Memory.m2
OBJS =		MCArgs.o MCBase.o MCBigSet.o MCFatal.o MCHalfword.o MCKey.o \
		MCMain.o MCMnemonics.o MCOperation.o MCP1IO.o MCP1Ident.o \
		MCP1Public.o MCP1Reals.o MCP2IO.o MCP2Ident.o MCP2Public.o \
		MCP2Referen.o MCP3IO.o MCP3Ident.o MCP3Public.o \
		MCP4Attribu.o MCP4BasicOp.o MCP4Blocks.o MCP4CodeSys.o \
		MCP4Expr.o MCP4Global.o MCP4In.o MCP4Public.o MCP4Registe.o \
		MCP4Scanner.o MCP4Stack.o MCP4Stateme.o MCP4Types.o \
		MCPass1.o MCPass2.o MCPass3.o MCPass4.o MCSuffixes.o \
		MCSymFile.o MCSymFileDe.o MCTypes.o Memory.o
SYMS =		
REFS =		MCArgs.r MCBase.r MCBigSet.r MCFatal.r MCHalfword.r MCKey.r \
		MCMain.r MCMnemonics.r MCOperation.r MCP1IO.r MCP1Ident.r \
		MCP1Public.r MCP1Reals.r MCP2IO.r MCP2Ident.r MCP2Public.r \
		MCP2Referen.r MCP3IO.r MCP3Ident.r MCP3Public.r \
		MCP4Attribu.r MCP4BasicOp.r MCP4Blocks.r MCP4CodeSys.r \
		MCP4Expr.r MCP4Global.r MCP4In.r MCP4Public.r MCP4Registe.r \
		MCP4Scanner.r MCP4Stack.r MCP4Stateme.r MCP4Types.r \
		MCPass1.r MCPass2.r MCPass3.r MCPass4.r MCSuffixes.r \
		MCSymFile.r MCSymFileDe.r MCTypes.r Memory.r
# {precious}
.PRECIOUS:	SYM
# {all}
T =		modula
all:		$T
# {linkage}
LIBS =		
LDFLAGS =	
$T:		MCArgs.o MCBase.o MCBigSet.o MCFatal.o MCHalfword.o MCKey.o \
		MCMain.o MCMnemonics.o MCOperation.o MCP1IO.o MCP1Ident.o \
		MCP1Public.o MCP1Reals.o MCP2IO.o MCP2Ident.o MCP2Public.o \
		MCP2Referen.o MCP3IO.o MCP3Ident.o MCP3Public.o \
		MCP4Attribu.o MCP4BasicOp.o MCP4Blocks.o MCP4CodeSys.o \
		MCP4Expr.o MCP4Global.o MCP4In.o MCP4Public.o MCP4Registe.o \
		MCP4Scanner.o MCP4Stack.o MCP4Stateme.o MCP4Types.o \
		MCPass1.o MCPass2.o MCPass3.o MCPass4.o MCSuffixes.o \
		MCSymFile.o MCSymFileDe.o MCTypes.o Memory.o
		$(M2C) $(MFLAGS) -o $@ $(LDFLAGS) MCArgs.o MCBase.o \
		MCBigSet.o MCFatal.o MCHalfword.o MCKey.o MCMain.o \
		MCMnemonics.o MCOperation.o MCP1IO.o MCP1Ident.o \
		MCP1Public.o MCP1Reals.o MCP2IO.o MCP2Ident.o MCP2Public.o \
		MCP2Referen.o MCP3IO.o MCP3Ident.o MCP3Public.o \
		MCP4Attribu.o MCP4BasicOp.o MCP4Blocks.o MCP4CodeSys.o \
		MCP4Expr.o MCP4Global.o MCP4In.o MCP4Public.o MCP4Registe.o \
		MCP4Scanner.o MCP4Stack.o MCP4Stateme.o MCP4Types.o \
		MCPass1.o MCPass2.o MCPass3.o MCPass4.o MCSuffixes.o \
		MCSymFile.o MCSymFileDe.o MCTypes.o Memory.o $(LIBS)
# {dependencies}
SYM(MCArgs.sy):	MCArgs.d
		$(M2C) $(MFLAGS) MCArgs.d
MCArgs.o:	../../lib/SYM(Arguments.sy) ../../lib/SYM(FtdIO.sy) \
		SYM(MCArgs.sy) SYM(MCBase.sy) SYM(MCFatal.sy) \
		SYM(MCP1Public.sy) SYM(MCP2Public.sy) SYM(MCP3Public.sy) \
		SYM(MCP4Public.sy) SYM(MCSuffixes.sy) SYM(MCSymFile.sy) \
		SYM(Memory.sy) ../../lib/SYM(S.sy) ../../lib/SYM(StdIO.sy) \
		../../lib/SYM(Strings.sy) ../../lib/SYM(SysExit.sy) \
		../../lib/SYM(SysGetpid.sy) ../../lib/SYM(SysUnlink.sy) \
		../../lib/SYM(SystemTypes.sy)
SYM(MCBase.sy):	MCBase.d
		$(M2C) $(MFLAGS) MCBase.d
MCBase.o:	SYM(MCBase.sy)
SYM(MCBigSet.sy): MCBigSet.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCBigSet.d
MCBigSet.o:	SYM(MCBase.sy) SYM(MCBigSet.sy) SYM(Memory.sy)
SYM(MCFatal.sy): MCFatal.d
		$(M2C) $(MFLAGS) MCFatal.d
MCFatal.o:	../../lib/SYM(Errno.sy) ../../lib/SYM(FtdIO.sy) \
		SYM(MCBase.sy) SYM(MCFatal.sy) SYM(MCP1Public.sy) \
		SYM(MCP2Public.sy) SYM(MCP3Public.sy) SYM(MCP4Public.sy) \
		../../lib/SYM(StdIO.sy) ../../lib/SYM(SysExit.sy) \
		../../lib/SYM(SysPerror.sy)
SYM(MCHalfword.sy): MCHalfword.d ../../lib/SYM(StdIO.sy)
		$(M2C) $(MFLAGS) MCHalfword.d
MCHalfword.o:	SYM(MCFatal.sy) ../../lib/SYM(StdIO.sy) SYM(MCHalfword.sy)
MCKey.o:	../../lib/SYM(Calendar.sy) SYM(MCBase.sy) SYM(MCKey.sy) \
		../../lib/SYM(SysGetpid.sy) ../../lib/SYM(SysGetuid.sy)
SYM(MCKey.sy):	MCKey.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCKey.d
MCMain.o:	../../lib/SYM(FtdIO.sy) SYM(MCArgs.sy) SYM(MCBase.sy) \
		SYM(MCP1Public.sy) SYM(MCP2Public.sy) SYM(MCP3Public.sy) \
		SYM(MCP4Public.sy) SYM(MCPass1.sy) SYM(MCPass2.sy) \
		SYM(MCPass3.sy) SYM(MCPass4.sy) SYM(MCSymFile.sy) \
		../../lib/SYM(StdIO.sy) ../../lib/SYM(SysExit.sy)
SYM(MCMnemonics.sy): MCMnemonics.d
		$(M2C) $(MFLAGS) MCMnemonics.d
MCMnemonics.o:	SYM(MCMnemonics.sy)
SYM(MCOperation.sy): MCOperation.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCOperation.d
MCOperation.o:	SYM(MCBase.sy) SYM(MCBigSet.sy) SYM(MCOperation.sy) \
		SYM(MCP1Reals.sy) SYM(MCTypes.sy) SYM(Memory.sy)
SYM(MCP1IO.sy):	MCP1IO.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP1IO.d
MCP1IO.o:	../../lib/SYM(Archive.sy) ../../lib/SYM(FtdIO.sy) \
		SYM(MCBase.sy) SYM(MCBigSet.sy) SYM(MCFatal.sy) \
		SYM(MCP1IO.sy) SYM(MCP1Public.sy) SYM(MCP1Reals.sy) \
		SYM(MCSymFileDe.sy) SYM(MCTypes.sy) SYM(Memory.sy) \
		../../lib/SYM(StdIO.sy) ../../lib/SYM(SystemTypes.sy) \
		SYM(MCHalfword.sy)
SYM(MCP1Ident.sy): MCP1Ident.d
		$(M2C) $(MFLAGS) MCP1Ident.d
MCP1Ident.o:	SYM(MCBase.sy) SYM(MCP1IO.sy) SYM(MCP1Ident.sy) \
		SYM(Memory.sy)
SYM(MCP1Public.sy): MCP1Public.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP1Public.d
MCP1Public.o:	SYM(MCP1Public.sy)
SYM(MCP1Reals.sy): MCP1Reals.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP1Reals.d
MCP1Reals.o:	SYM(MCBase.sy) SYM(MCP1Reals.sy) SYM(Memory.sy)
SYM(MCP2IO.sy):	MCP2IO.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP2IO.d
MCP2IO.o:	../../lib/SYM(FtdIO.sy) SYM(MCBase.sy) SYM(MCFatal.sy) \
		SYM(MCP2IO.sy) SYM(MCP2Public.sy) ../../lib/SYM(StdIO.sy) \
		SYM(MCHalfword.sy)
SYM(MCP2Ident.sy): MCP2Ident.d SYM(MCBase.sy) SYM(MCP2IO.sy)
		$(M2C) $(MFLAGS) MCP2Ident.d
MCP2Ident.o:	SYM(MCBase.sy) SYM(MCP2IO.sy) SYM(MCP2Ident.sy) \
		SYM(Memory.sy)
SYM(MCP2Public.sy): MCP2Public.d
		$(M2C) $(MFLAGS) MCP2Public.d
MCP2Public.o:	SYM(MCP2Public.sy)
SYM(MCP2Referen.sy): MCP2Referen.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP2Referen.d
MCP2Referen.o:	SYM(MCBase.sy) SYM(MCFatal.sy) SYM(MCP2IO.sy) \
		SYM(MCP2Public.sy) SYM(MCP2Referen.sy) \
		../../lib/SYM(StdIO.sy) SYM(MCHalfword.sy)
SYM(MCP3IO.sy):	MCP3IO.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP3IO.d
MCP3IO.o:	../../lib/SYM(FtdIO.sy) SYM(MCBase.sy) SYM(MCFatal.sy) \
		SYM(MCP3IO.sy) SYM(MCP3Public.sy) SYM(Memory.sy) \
		../../lib/SYM(StdIO.sy) ../../lib/SYM(SystemTypes.sy) \
		SYM(MCHalfword.sy)
SYM(MCP3Ident.sy): MCP3Ident.d SYM(MCBase.sy) SYM(MCP3IO.sy)
		$(M2C) $(MFLAGS) MCP3Ident.d
MCP3Ident.o:	SYM(MCBase.sy) SYM(MCP3IO.sy) SYM(MCP3Ident.sy) \
		SYM(Memory.sy)
SYM(MCP3Public.sy): MCP3Public.d
		$(M2C) $(MFLAGS) MCP3Public.d
MCP3Public.o:	SYM(MCP3Public.sy)
SYM(MCP4Attribu.sy): MCP4Attribu.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP4Attribu.d
MCP4Attribu.o:	SYM(MCBase.sy) SYM(MCP4Attribu.sy) SYM(MCP4Global.sy) \
		SYM(Memory.sy)
SYM(MCP4BasicOp.sy): MCP4BasicOp.d SYM(MCBase.sy) SYM(MCP4Attribu.sy)
		$(M2C) $(MFLAGS) MCP4BasicOp.d
MCP4BasicOp.o:	SYM(MCBase.sy) SYM(MCMnemonics.sy) SYM(MCP4Attribu.sy) \
		SYM(MCP4BasicOp.sy) SYM(MCP4Blocks.sy) SYM(MCP4CodeSys.sy) \
		SYM(MCP4Global.sy) SYM(MCP4Registe.sy) SYM(MCP4Scanner.sy) \
		SYM(MCP4Stack.sy) SYM(MCP4Types.sy) SYM(Memory.sy)
SYM(MCP4Blocks.sy): MCP4Blocks.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP4Blocks.d
MCP4Blocks.o:	SYM(MCBase.sy) SYM(MCMnemonics.sy) SYM(MCP4Attribu.sy) \
		SYM(MCP4BasicOp.sy) SYM(MCP4Blocks.sy) SYM(MCP4CodeSys.sy) \
		SYM(MCP4Global.sy) SYM(MCP4Public.sy) SYM(MCP4Registe.sy) \
		SYM(MCP4Scanner.sy) SYM(MCP4Stack.sy) SYM(MCP4Stateme.sy) \
		SYM(MCP4Types.sy)
SYM(MCP4CodeSys.sy): MCP4CodeSys.d SYM(MCBase.sy) SYM(MCMnemonics.sy)
		$(M2C) $(MFLAGS) MCP4CodeSys.d
MCP4CodeSys.o:	../../lib/SYM(ASCII.sy) ../../lib/SYM(Conversions.sy) \
		SYM(MCBase.sy) SYM(MCFatal.sy) SYM(MCMnemonics.sy) \
		SYM(MCP4Attribu.sy) SYM(MCP4CodeSys.sy) SYM(MCP4Global.sy) \
		SYM(MCP4Public.sy) SYM(MCP4Scanner.sy) SYM(MCP4Types.sy) \
		SYM(Memory.sy) ../../lib/SYM(StdIO.sy) \
		../../lib/SYM(SysExit.sy) ../../lib/SYM(SystemTypes.sy)
SYM(MCP4Expr.sy): MCP4Expr.d SYM(MCBase.sy) SYM(MCP4Attribu.sy)
		$(M2C) $(MFLAGS) MCP4Expr.d
MCP4Expr.o:	SYM(MCBase.sy) SYM(MCBigSet.sy) SYM(MCMnemonics.sy) \
		SYM(MCP4Attribu.sy) SYM(MCP4BasicOp.sy) SYM(MCP4Blocks.sy) \
		SYM(MCP4CodeSys.sy) SYM(MCP4Expr.sy) SYM(MCP4Global.sy) \
		SYM(MCP4Registe.sy) SYM(MCP4Scanner.sy) SYM(MCP4Stack.sy) \
		SYM(MCP4Stateme.sy) SYM(MCP4Types.sy) SYM(Memory.sy) \
		../../lib/SYM(Sys.sy)
SYM(MCP4Global.sy): MCP4Global.d
		$(M2C) $(MFLAGS) MCP4Global.d
MCP4Global.o:	../../lib/SYM(FtdIO.sy) SYM(MCFatal.sy) SYM(MCP4Global.sy) \
		SYM(MCP4Public.sy) SYM(MCP4Scanner.sy) \
		../../lib/SYM(StdIO.sy) SYM(MCHalfword.sy)
SYM(MCP4In.sy):	MCP4In.d
		$(M2C) $(MFLAGS) MCP4In.d
MCP4In.o:	../../lib/SYM(FtdIO.sy) SYM(MCFatal.sy) SYM(MCP4In.sy) \
		SYM(MCP4Public.sy) ../../lib/SYM(StdIO.sy) \
		SYM(MCHalfword.sy)
SYM(MCP4Public.sy): MCP4Public.d
		$(M2C) $(MFLAGS) MCP4Public.d
MCP4Public.o:	SYM(MCP4Public.sy)
SYM(MCP4Registe.sy): MCP4Registe.d SYM(MCBase.sy) SYM(MCP4Attribu.sy)
		$(M2C) $(MFLAGS) MCP4Registe.d
MCP4Registe.o:	SYM(MCBase.sy) SYM(MCMnemonics.sy) SYM(MCP4Attribu.sy) \
		SYM(MCP4CodeSys.sy) SYM(MCP4Global.sy) SYM(MCP4Registe.sy) \
		SYM(MCP4Stack.sy)
SYM(MCP4Scanner.sy): MCP4Scanner.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP4Scanner.d
MCP4Scanner.o:	../../lib/SYM(Conversions.sy) SYM(MCBase.sy) \
		SYM(MCP4CodeSys.sy) SYM(MCP4In.sy) SYM(MCP4Public.sy) \
		SYM(MCP4Scanner.sy)
SYM(MCP4Stack.sy): MCP4Stack.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCP4Stack.d
MCP4Stack.o:	SYM(MCBase.sy) SYM(MCP4Attribu.sy) SYM(MCP4CodeSys.sy) \
		SYM(MCP4Global.sy) SYM(MCP4Stack.sy) SYM(Memory.sy)
SYM(MCP4Stateme.sy): MCP4Stateme.d SYM(MCBase.sy) SYM(MCP4Attribu.sy)
		$(M2C) $(MFLAGS) MCP4Stateme.d
MCP4Stateme.o:	SYM(MCBase.sy) SYM(MCMnemonics.sy) SYM(MCP4Attribu.sy) \
		SYM(MCP4BasicOp.sy) SYM(MCP4Blocks.sy) SYM(MCP4CodeSys.sy) \
		SYM(MCP4Expr.sy) SYM(MCP4Global.sy) SYM(MCP4Registe.sy) \
		SYM(MCP4Scanner.sy) SYM(MCP4Stack.sy) SYM(MCP4Stateme.sy) \
		SYM(MCP4Types.sy) SYM(Memory.sy)
SYM(MCP4Types.sy): MCP4Types.d SYM(MCBase.sy) SYM(MCP4Attribu.sy)
		$(M2C) $(MFLAGS) MCP4Types.d
MCP4Types.o:	SYM(MCBase.sy) SYM(MCP4Attribu.sy) SYM(MCP4Global.sy) \
		SYM(MCP4Types.sy) ../../lib/SYM(Storage.sy)
SYM(MCPass1.sy): MCPass1.d
		$(M2C) $(MFLAGS) MCPass1.d
MCPass1.o:	SYM(MCBase.sy) SYM(MCP1IO.sy) SYM(MCP1Ident.sy) \
		SYM(MCP1Public.sy) SYM(MCPass1.sy)
SYM(MCPass2.sy): MCPass2.d
		$(M2C) $(MFLAGS) MCPass2.d
MCPass2.o:	SYM(MCBase.sy) SYM(MCBigSet.sy) SYM(MCFatal.sy) \
		SYM(MCKey.sy) SYM(MCOperation.sy) SYM(MCP1Reals.sy) \
		SYM(MCP2IO.sy) SYM(MCP2Ident.sy) SYM(MCP2Public.sy) \
		SYM(MCP2Referen.sy) SYM(MCPass2.sy) SYM(MCTypes.sy) \
		SYM(Memory.sy)
SYM(MCPass3.sy): MCPass3.d
		$(M2C) $(MFLAGS) MCPass3.d
MCPass3.o:	SYM(MCBase.sy) SYM(MCBigSet.sy) SYM(MCOperation.sy) \
		SYM(MCP1Reals.sy) SYM(MCP3IO.sy) SYM(MCP3Ident.sy) \
		SYM(MCP3Public.sy) SYM(MCPass3.sy) SYM(MCTypes.sy) \
		SYM(Memory.sy)
SYM(MCPass4.sy): MCPass4.d
		$(M2C) $(MFLAGS) MCPass4.d
MCPass4.o:	SYM(MCP4Blocks.sy) SYM(MCP4Global.sy) SYM(MCP4In.sy) \
		SYM(MCPass4.sy)
SYM(MCSuffixes.sy): MCSuffixes.d
		$(M2C) $(MFLAGS) MCSuffixes.d
MCSuffixes.o:	SYM(MCP4Global.sy) SYM(MCSuffixes.sy) \
		../../lib/SYM(Strings.sy)
SYM(MCSymFile.sy): MCSymFile.d
		$(M2C) $(MFLAGS) MCSymFile.d
MCSymFile.o:	../../lib/SYM(Conversions.sy) ../../lib/SYM(FtdIO.sy) \
		SYM(MCBase.sy) SYM(MCFatal.sy) SYM(MCSymFile.sy) \
		SYM(MCSymFileDe.sy) SYM(Memory.sy) ../../lib/SYM(StdIO.sy) \
		SYM(MCHalfword.sy)
SYM(MCSymFileDe.sy): MCSymFileDe.d
		$(M2C) $(MFLAGS) MCSymFileDe.d
MCSymFileDe.o:	SYM(MCSymFileDe.sy)
SYM(MCTypes.sy): MCTypes.d SYM(MCBase.sy)
		$(M2C) $(MFLAGS) MCTypes.d
MCTypes.o:	SYM(MCBase.sy) SYM(MCTypes.sy) SYM(Memory.sy)
SYM(Memory.sy):	Memory.d
		$(M2C) $(MFLAGS) Memory.d
Memory.o:	SYM(MCBase.sy) SYM(MCFatal.sy) SYM(Memory.sy) \
		../../lib/SYM(Storage.sy) ../../lib/SYM(SysLocation.sy)
#
tags:		$(TAGSRC)
		mtags $(TAGSRC)
#
SPOOL =		lpr
pr:		Pr.date
Pr.date:	$(SRC)
		pr $? | $(SPOOL)
		-touch Pr.date
#
clean:		; rm -f $(OBJS) $(SYMS) $(REFS)
#
LibDir :=	/usr/local/lib/modula
.PHONY:		install
install:	$(LibDir)/$T $(LibDir)/m2_error
$(LibDir)/$T:	$T
		cp $< $@
$(LibDir)/m2_error:	m2_error
		cp $< $@
