.\" ---------------------------------------------------------------------------
.\" Ulm's Modula-2 System Documentation
.\" Copyright (C) 1983-1997 by University of Ulm, SAI, 89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.TH Sys 3 "Ulm's Modula-2 System"
.SH NAME
Sys \- UNIX system calls
.SH SYNOPSIS
.Pg
CONST
   syscall          =   0;        sigsendsys       = 108;
   exit             =   1;        hrtsys           = 109;
   fork             =   2;        acancel          = 110;
   read             =   3;        async            = 111;
   write            =   4;        priocntlsys      = 112;
   open             =   5;        pathconf         = 113;
   close            =   6;        mincore          = 114;
   wait             =   7;        mmap             = 115;
   creat            =   8;        mprotect         = 116;
   link             =   9;        munmap           = 117;
   unlink           =  10;        fpathconf        = 118;
   exec             =  11;        vfork            = 119;
   chdir            =  12;        fchdir           = 120;
   time             =  13;        readv            = 121;
   mknod            =  14;        writev           = 122;
   chmod            =  15;        xstat            = 123;
   chown            =  16;        lxstat           = 124;
   brk              =  17;        fxstat           = 125;
   stat             =  18;        xmknod           = 126;
   lseek            =  19;        clocal           = 127;
   getpid           =  20;        setrlimit        = 128;
   mount            =  21;        getrlimit        = 129;
   umount           =  22;        lchown           = 130;
   setuid           =  23;        memcntl          = 131;
   getuid           =  24;        getpmsg          = 132;
   stime            =  25;        putpmsg          = 133;
   ptrace           =  26;        rename           = 134;
   alarm            =  27;        uname            = 135;
   fstat            =  28;        setegid          = 136;
   pause            =  29;        sysconfig        = 137;
   utime            =  30;        adjtime          = 138;
   stty             =  31;        systeminfo       = 139;
   gtty             =  32;        seteuid          = 141;
   access           =  33;        vtrace           = 142;
   nice             =  34;        fork1            = 143;
   statfs           =  35;        sigtimedwait     = 144;
   sync             =  36;        lwpInfo          = 145;
   kill             =  37;        yield            = 146;
   fstatfs          =  38;        lwpSemaWait      = 147;
   pgrpsys          =  39;        lwpSemaPost      = 148;
   xenix            =  40;        modctl           = 152;
   dup              =  41;        fchroot          = 153;
   pipe             =  42;        utimes           = 154;
   times            =  43;        vhangup          = 155;
   profil           =  44;        gettimeofday     = 156;
   plock            =  45;        getitimer        = 157;
   setgid           =  46;        setitimer        = 158;
   getgid           =  47;        lwpCreate        = 159;
   signal           =  48;        lwpExit          = 160;
   msgsys           =  49;        lwpSuspend       = 161;
   syssun           =  50;        lwpContinue      = 162;
   sysi86           =  50;        lwpKill          = 163;
   sysppc           =  50;        lwpSelf          = 164;
   acct             =  51;        lwpSetprivate    = 165;
   shmsys           =  52;        lwpGetprivate    = 166;
   semsys           =  53;        lwpWait          = 167;
   ioctl            =  54;        lwpMutexUnlock   = 168;
   uadmin           =  55;        lwpMutexLock     = 169;
   utssys           =  57;        lwpCondWait      = 170;
   fdsync           =  58;        lwpCondSignal    = 171;
   execve           =  59;        lwpCondBroadcast = 172;
   umask            =  60;        pread            = 173;
   chroot           =  61;        pwrite           = 174;
   fcntl            =  62;        llseek           = 175;
   ulimit           =  63;        instSync         = 176;
   rmdir            =  79;        kaio             = 178;
   mkdir            =  80;        tsolsys          = 184;
   getdents         =  81;        acl              = 185;
   sysfs            =  84;        auditsys         = 186;
   getmsg           =  85;        processorBind    = 187;
   putmsg           =  86;        processorInfo    = 188;
   poll             =  87;        pOnline          = 189;
   lstat            =  88;        sigqueue         = 190;
   symlink          =  89;        clockGettime     = 191;
   readlink         =  90;        clockSettime     = 192;
   setgroups        =  91;        clockGetres      = 193;
   getgroups        =  92;        timerCreate      = 194;
   fchmod           =  93;        timerDelete      = 195;
   fchown           =  94;        timerSettime     = 196;
   sigprocmask      =  95;        timerGettime     = 197;
   sigsuspend       =  96;        timerGetoverrun  = 198;
   sigaltstack      =  97;        nanosleep        = 199;
   sigaction        =  98;        facl             = 200;
   sigpending       =  99;        door             = 201;
   context          = 100;        setreuid         = 202;
   evsys            = 101;        setregid         = 203;
   evtrapret        = 102;        installUtrap     = 204;
   statvfs          = 103;        signotifywait    = 210;
   fstatvfs         = 104;        lwpSigredirect   = 211;
   nfssys           = 106;        lwpAlarm         = 212;
   waitsys          = 107;
.Pe
.SH DESCRIPTION
.I Sys
exports the UNIX system call numbers.
The system call numbers are extracted from
\fI/usr/include/sys/syscall.h\fP.
System call numbers are given as first argument to
\fBSYSTEM.UNIXCALL\fP.
.SH FILES
.Tb /usr/include/sys/syscall.h
.Tp /usr/include/sys/syscall.h
system call numbers
.Te
.SH "SEE ALSO"
.Tb SystemTypes(3)
.Tp Errno(3)
error codes returned by system calls
.Tp SystemTypes(3)
definition of some types needed for system calls
.Te
.SH BUGS
Not every system call described in chapter 2 of the UNIX manual
is a unique system call,
e.g. \fIsemsys\fP realizes all semaphore operations.
.PP
The synopsis above is a snapshot of Solaris 2.5.1 and may be
different on your system.
.\" ---------------------------------------------------------------------------
.\" $Id: Sys.3,v 1.2 1997/02/26 18:45:53 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: Sys.3,v $
.\" Revision 1.2  1997/02/26  18:45:53  borchert
.\" adapted to Solaris 2.5.1
.\"
.\" Revision 1.1  1997/02/25  18:30:15  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
