.\" ---------------------------------------------------------------------------
.\" Ulm's Modula-2 System Documentation
.\" Copyright (C) 1983-1997 by University of Ulm, SAI, 89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.TH SysFcntl 3 "Ulm's Modula-2 System"
.SH NAME
SysFcntl \- file control operations
.SH SYNOPSIS
.Pg
TYPE FcntlRequest = (dupfd, getfd, setfd, getfl, setfl, getown,
                     setown, getlk, setlk, setlkw);
.sp 0.7
PROCEDURE Fcntl(fd: CARDINAL; cmd: FcntlRequest; VAR arg: WORD) : BOOLEAN;
.Pe
.SH DESCRIPTION
.I SysFcntl
offers various file control operations for open files.
See \fIfcntl(2)\fP for a detailed description.
.SH DIAGNOSTICS
On failure, \fBFALSE\fP is returned and \fIErrno.errno\fP is set.
.SH "SEE ALSO"
\fIfcntl(2)\fP
.\" ---------------------------------------------------------------------------
.\" $Id: SysFcntl.3,v 1.1 1997/02/26 08:46:53 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: SysFcntl.3,v $
.\" Revision 1.1  1997/02/26  08:46:53  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
