.\" ---------------------------------------------------------------------------
.\" Ulm's Modula-2 System Documentation
.\" Copyright (C) 1983-1997 by University of Ulm, SAI, 89069 Ulm, Germany
.\" ---------------------------------------------------------------------------
.TH SysGetpid 3 "Ulm's Modula-2 System"
.SH NAME
SysGetpid \- get process ID of the current process
.SH SYNOPSIS
.Pg
PROCEDURE Getpid(): SystemTypes.ProcessId;
.Pe
.SH DESCRIPTION
.I Getpid
returns the process ID of the current process.
.SH "SEE ALSO"
\fIgetpid(2)\fP, \fISysGetuid(3)\fP
.SH AUTHOR
The module has been written by Martin Hasch,
this manual page is due to Andreas Borchert.
.\" ---------------------------------------------------------------------------
.\" $Id: SysGetpid.3,v 1.1 1997/02/26 08:56:09 borchert Exp $
.\" ---------------------------------------------------------------------------
.\" $Log: SysGetpid.3,v $
.\" Revision 1.1  1997/02/26  08:56:09  borchert
.\" Initial revision
.\"
.\" ---------------------------------------------------------------------------
